version: '3.8'

services:
  api_gateway:
    image: node:alpine
    container_name: api_gateway
    working_dir: /app
    volumes:
      - ./Backend/api_gateway:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - btp_db_network
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  authentification_service:
    image: node:alpine
    container_name: authentification_service
    working_dir: /app
    volumes:
      - ./Backend/authentification_service:/app
      - /app/node_modules
    ports:
      - 3001:3001
    networks:
      - btp_db_network
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=user
      - PG_PASSWORD=password
      - PG_DATABASE=btp_db
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  users_service:
    image: node:alpine
    container_name: users_service
    working_dir: /app
    volumes:
      - ./Backend/users_service:/app
      - /app/node_modules
    ports:
      - 3002:3002
    networks:
      - btp_db_network
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=user
      - PG_PASSWORD=password
      - PG_DATABASE=btp_db
      - REDIS_URL=redis://redis:6379
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: btp_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data 
      - ./Conception/Database:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d btp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: btp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: always

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
      - ./Conception/Messagerie_db:/docker-entrypoint-initdb.d
    networks:
      - btp_db_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - btp_db_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  btp_db_network:
    driver: bridge

volumes:
  pg_data:
  mongo_data:
